#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { spawn, spawnSync } from "node:child_process";
import process from "node:process";

const DEFAULT_CONFIG = {
  mode: "local",
  ollama: {
    pullModels: ["qwen3:8b", "nomic-embed-text"],
  },
  env: {
    OLLAMA_HOST: "http://127.0.0.1:11434",
    CHAT_MODEL: "qwen3:8b",
    EMBED_MODEL: "nomic-embed-text",
    EXTRACT_MODEL: "qwen3:8b",
    MAX_CONCURRENCY: "4",
    REQUEST_TIMEOUT: "120",
    LOG_LEVEL: "INFO",
    SESSION_MAX_TURNS: "20",
    SESSION_TTL_SECONDS: "3600",
    SESSION_STORAGE_DIR: "data/sessions",
  },
  local: {
    python: "python3",
    useVenv: true,
    venvDir: ".venv",
    autoCreateVenv: true,
    autoInstallDeps: true,
    autoStartOllama: true,
    autoPullModels: true,
    uvicornHost: "0.0.0.0",
    uvicornPort: 8000,
    reload: true,
  },
  docker: {
    composeFile: "docker-compose.yml",
    detached: true,
    autoPullModels: true,
  },
};

function parseArgs(argv) {
  const options = {
    configPath: "startup.config.json",
    mode: null,
  };

  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];

    if (arg === "--config") {
      options.configPath = argv[i + 1] || options.configPath;
      i += 1;
      continue;
    }

    if (arg === "--mode") {
      options.mode = argv[i + 1] || null;
      i += 1;
      continue;
    }

    if (arg === "--help" || arg === "-h") {
      printHelp();
      process.exit(0);
    }
  }

  return options;
}

function printHelp() {
  console.log(`FastAPI + Ollama one-click launcher\n\nUsage:\n  npm start\n  npm run start:local\n  npm run start:docker\n  node scripts/start.mjs --config startup.config.json --mode local\n`);
}

function isPlainObject(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function deepMerge(base, override) {
  if (!isPlainObject(base) || !isPlainObject(override)) {
    return override;
  }

  const merged = { ...base };

  for (const [key, value] of Object.entries(override)) {
    if (isPlainObject(value) && isPlainObject(base[key])) {
      merged[key] = deepMerge(base[key], value);
      continue;
    }

    merged[key] = value;
  }

  return merged;
}

function readJsonFile(filePath) {
  const raw = fs.readFileSync(filePath, "utf-8");
  return JSON.parse(raw);
}

function runCommand(command, args, cwd) {
  const display = [command, ...args].join(" ");
  console.log(`\n$ ${display}`);

  const result = spawnSync(command, args, {
    cwd,
    stdio: "inherit",
    env: process.env,
  });

  if (result.error) {
    throw result.error;
  }

  if (result.status !== 0) {
    throw new Error(`Command failed (${result.status}): ${display}`);
  }
}

function writeEnvFile(projectRoot, envMap) {
  const envLines = Object.entries(envMap).map(([key, value]) => `${key}=${String(value)}`);
  const content = [
    "# Auto-generated by scripts/start.mjs",
    ...envLines,
    "",
  ].join("\n");

  const envPath = path.join(projectRoot, ".env");
  fs.writeFileSync(envPath, content, "utf-8");
  console.log(`Wrote ${path.relative(projectRoot, envPath)} from startup config.`);
}

function uniqueModels(config) {
  const base = Array.isArray(config.ollama?.pullModels) ? config.ollama.pullModels : [];
  return Array.from(new Set(base.filter(Boolean)));
}

function resolveLocalPython(projectRoot, localConfig) {
  if (!localConfig.useVenv) {
    return localConfig.python;
  }

  return path.join(projectRoot, localConfig.venvDir, "bin", "python");
}

function ensureVenv(projectRoot, localConfig) {
  if (!localConfig.useVenv || !localConfig.autoCreateVenv) {
    return;
  }

  const venvPython = path.join(projectRoot, localConfig.venvDir, "bin", "python");
  if (fs.existsSync(venvPython)) {
    return;
  }

  runCommand(localConfig.python, ["-m", "venv", localConfig.venvDir], projectRoot);
}

function pullOllamaModels(projectRoot, models) {
  for (const model of models) {
    runCommand("ollama", ["pull", model], projectRoot);
  }
}

function sleep(ms) {
  return new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}

function canReachOllama(projectRoot) {
  const result = spawnSync("ollama", ["list"], {
    cwd: projectRoot,
    stdio: "ignore",
    env: process.env,
  });
  return result.status === 0;
}

async function ensureOllamaRunning(projectRoot, config) {
  const localConfig = config.local;
  const ollamaHost = String(config.env?.OLLAMA_HOST || "");
  const isLocalHost = ollamaHost.includes("127.0.0.1") || ollamaHost.includes("localhost");

  if (!localConfig.autoStartOllama || !isLocalHost || canReachOllama(projectRoot)) {
    return;
  }

  console.log("\nOllama is not reachable. Starting `ollama serve` in background...");
  const child = spawn("ollama", ["serve"], {
    cwd: projectRoot,
    detached: true,
    stdio: "ignore",
    env: process.env,
  });
  child.unref();

  for (let i = 0; i < 20; i += 1) {
    await sleep(500);
    if (canReachOllama(projectRoot)) {
      console.log("Ollama is ready.");
      return;
    }
  }

  throw new Error("Ollama did not become ready after starting `ollama serve`.");
}

async function startLocal(projectRoot, config) {
  const localConfig = config.local;

  writeEnvFile(projectRoot, config.env);
  await ensureOllamaRunning(projectRoot, config);
  ensureVenv(projectRoot, localConfig);

  const pythonExec = resolveLocalPython(projectRoot, localConfig);

  if (localConfig.autoInstallDeps) {
    runCommand(pythonExec, ["-m", "pip", "install", "-r", "requirements.txt"], projectRoot);
  }

  if (localConfig.autoPullModels) {
    pullOllamaModels(projectRoot, uniqueModels(config));
  }

  const uvicornArgs = [
    "-m",
    "uvicorn",
    "app.main:app",
    "--host",
    String(localConfig.uvicornHost),
    "--port",
    String(localConfig.uvicornPort),
  ];

  if (localConfig.reload) {
    uvicornArgs.push("--reload");
  }

  runCommand(pythonExec, uvicornArgs, projectRoot);
}

function startDocker(projectRoot, config) {
  const dockerConfig = config.docker;
  const composeArgs = ["compose", "-f", dockerConfig.composeFile, "up"];

  if (dockerConfig.detached) {
    composeArgs.push("-d");
  }

  runCommand("docker", composeArgs, projectRoot);

  if (dockerConfig.autoPullModels) {
    if (!dockerConfig.detached) {
      console.log("Skip model pull because docker.detached=false keeps compose attached.");
      return;
    }

    for (const model of uniqueModels(config)) {
      runCommand(
        "docker",
        ["compose", "-f", dockerConfig.composeFile, "exec", "ollama", "ollama", "pull", model],
        projectRoot,
      );
    }
  }
}

async function main() {
  const projectRoot = process.cwd();
  const options = parseArgs(process.argv.slice(2));
  const configPath = path.resolve(projectRoot, options.configPath);

  if (!fs.existsSync(configPath)) {
    throw new Error(`Missing config file: ${configPath}`);
  }

  const userConfig = readJsonFile(configPath);
  const config = deepMerge(DEFAULT_CONFIG, userConfig);

  if (options.mode) {
    config.mode = options.mode;
  }

  if (config.mode !== "local" && config.mode !== "docker") {
    throw new Error(`Invalid mode: ${config.mode}. Use \"local\" or \"docker\".`);
  }

  if (config.mode === "local") {
    await startLocal(projectRoot, config);
    return;
  }

  startDocker(projectRoot, config);
}

try {
  await main();
} catch (error) {
  console.error("\nLauncher failed:");
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
}
